spring:
  datasource:
    url: jdbc:h2:mem:test1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql