spring:
  datasource:
    url: jdbc:h2:mem:maindb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql